### PR TITLE
add capability to programatically dismiss top card

### PR DESCRIPTION
**Pull request by fouadkada**
adds capability to programatically dismiss top card.
I can't get animation to work.

### CODE REVIEW

**Comment by diogobernardino** [comment]
I don't see the point of having such specific dismiss-to-top functionality.

**Comment by fouadkada** [comment]
what if the developer wants to dismiss a card programatically based on some external event?

**Comment by diogobernardino** [comment]
The development of a library can't be driven by every feature that every developer wants to see on it. And remember you can always fork a project and develop the specifics on top of it. Of course I wouldn't completely discard the possibility of having such functionality, but certainly not at this phase.

Moreover, and more as a recommendation, while trying to contribute to a project, never make a PR without even having it fully working. Apparently this was the case: 

> "I can't get animation to work."

**Comment by fouadkada** [comment]
ok :)

**Pull request closed without merging**
